export const app = {
    API_URL: import.meta.env.VITE_API_URL,
    GOOGLE_MAPS_API_KEY: import.meta.env.VITE_GOOGLE_MAPS_API_KEY,
    GOOGLE_MAPS_MAP_ID: import.meta.env.VITE_GOOGLE_MAPS_MAP_ID,
    CLIENT_URL: import.meta.env.VITE_CLIENT_URL,
    WEBSITE_URL: import.meta.env.VITE_WEBSITE_URL,
    DEFAULT_PAGE_SIZE: 10,
    BIG_PAGE_SIZE: 50,
    PIPELINE_PAGE_SIZE: 1000,
    DEFAULT_PAGE: 1,
    FETCH_ALL: -1,
    EMPTY_DISPLAY: '-',
    PARENT_PREFIX: '-- ',
    DEFAULT_POSITION: 1,
    DEFAULT_CATEGORY: 1,
    CODE_PAD_LENGTH: 4,
    TAG_COLOR_DEFAULT: 'default',
    MAP_PROVIDER: import.meta.env.VITE_MAP_PROVIDER || 'leaflet',
}
